# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_CV1800_TPU)         += cv1800_tpu.o
cv1800_tpu-y += common/cvi_tpu_interface.o
cv1800_tpu-y += hal/cv181x/tpu_platform.o
cv1800_tpu-y += hal/cv181x/tpu_pmu.o
